//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Logs
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class LogManager
	{
		public virtual Log Log
		{
			get;
			set;
		}

		public virtual void GetLogs(object TypeLog)
		{
			throw new System.NotImplementedException();
		}

		public virtual void GetLogs(object TypeHomeDevice)
		{
			throw new System.NotImplementedException();
		}

		public virtual void GetLogs(object Date)
		{
			throw new System.NotImplementedException();
		}

	}
}

