//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface ActionAbstrract 
{
	object HomeDeviceTo { get;set; }

	object OpCode { get;set; }

	object Args { get;set; }

	object Enable { get;set; }

	object ID { get;set; }

	void Execute();

	void ToString();

}

