//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class NetworkManager
{
	public virtual Security Security
	{
		get;
		set;
	}

	public virtual Node Node
	{
		get;
		set;
	}

	public virtual HomeDeviceAbstract HomeDeviceAbstract
	{
		get;
		set;
	}

	public virtual void AddNewNode()
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddNewHomeDevice()
	{
		throw new System.NotImplementedException();
	}

}

