//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PowerSensor : HomeDeviceAbstract
{
	public virtual object CurrentConsumption
	{
		get;
		set;
	}

	public virtual object Sensibility
	{
		get;
		set;
	}

	public virtual object MaximumConsumption
	{
		get;
		set;
	}

	public virtual void RefreshState()
	{
		throw new System.NotImplementedException();
	}

}

