//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class RGBLight : HomeDeviceAbstract
{
	public virtual object Color
	{
		get;
		set;
	}

	public virtual object Mode
	{
		get;
		set;
	}

	public virtual object DefaultDegradeTime
	{
		get;
		set;
	}

	public virtual TypeModeRGBLight TypeModeRGBLight
	{
		get;
		set;
	}

	public virtual ModeRGBLight ModeRGBLight
	{
		get;
		set;
	}

	public virtual void White(object time)
	{
		throw new System.NotImplementedException();
	}

	public virtual void TurnOff(object time)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Invert(object time)
	{
		throw new System.NotImplementedException();
	}

	public virtual void ToColor(object Color, object time)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Random(object time)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Secuence(object Color[], object time)
	{
		throw new System.NotImplementedException();
	}

	public virtual void RandomSecuence(object Color[], object time)
	{
		throw new System.NotImplementedException();
	}

	public virtual void RefreshState()
	{
		throw new System.NotImplementedException();
	}

}

