//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Security
{
	public virtual object PanID
	{
		get;
		set;
	}

	public virtual object Channel
	{
		get;
		set;
	}

	public virtual object SecurityKey
	{
		get;
		set;
	}

	public virtual object ID
	{
		get;
		set;
	}

}

