//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TimeRestriction
{
	public virtual object Start
	{
		get;
		set;
	}

	public virtual object End
	{
		get;
		set;
	}

}

