//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Conexion.Products
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Base
	{
		public virtual object AnalogPorts
		{
			get;
			set;
		}

		public virtual object DeviceSignature
		{
			get;
			set;
		}

		public virtual object LittleEndian
		{
			get;
			set;
		}

		public virtual object NumPins
		{
			get;
			set;
		}

		public virtual object NumPorts
		{
			get;
			set;
		}

		public virtual object PWMPorts
		{
			get;
			set;
		}

		public virtual object UController
		{
			get;
			set;
		}

		public virtual object UnavailablePorts
		{
			get;
			set;
		}

	}
}

