//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Logs
{
	using Enums;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Log
	{
		public virtual object TypeHomeDevice
		{
			get;
			set;
		}

		public virtual object TypeLog
		{
			get;
			set;
		}

		public virtual object Date
		{
			get;
			set;
		}

		public virtual object Log
		{
			get;
			set;
		}

		public virtual TypeLog TypeLog
		{
			get;
			set;
		}

		public virtual void ToString()
		{
			throw new System.NotImplementedException();
		}

	}
}

