//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Conexion.Messages
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ToNetwork
	{
		public virtual void ToMessage(object AbstractAction)
		{
			throw new System.NotImplementedException();
		}

	}
}

