//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Enums
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public enum TypeCodeOP
	{
		DigitalWrite,
		DigitalSwitch,
		DigitalWriteTime,
		DigitalSwitchTime,
		DigitalRead,
		DigitalReadResponse,
		AnalogWrite,
		AnalogWriteTime,
		AnalogRead,
		AnalogReadResponse,
		Reset,
		RouteTableRead,
		RouteTableReadResponse,
		TimeWrite,
		TimeRead,
		TimeReponse,
		Warning,
		Error,
		ColorWrite,
		ColorWhiteRandom,
		ColorSecuenceWrite,
		ColorSortedSecuenceWrite,
		ColorReadResponse,
	}
}
