//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Buttom : HomeDeviceAbstract
{
	public virtual void Push()
	{
		throw new System.NotImplementedException();
	}

	public virtual void RefreshState()
	{
		throw new System.NotImplementedException();
	}

}

