//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Connector
{
	public virtual object Name
	{
		get;
		set;
	}

	public virtual object ID
	{
		get;
		set;
	}

	public virtual PinPort PinPort
	{
		get;
		set;
	}

	public virtual HomeDeviceAbstract HomeDevice
	{
		get;
		set;
	}

	public virtual Node Node
	{
		get;
		set;
	}

	public virtual TypeConnector Type
	{
		get;
		set;
	}

	public virtual TypeConnector1 TypeConnector1
	{
		get;
		set;
	}

}

