//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Dimmable : HomeDeviceAbstract
{
	public virtual object LastValue
	{
		get;
		set;
	}

	public virtual object Value
	{
		get;
		set;
	}

	public virtual DimmableSubtype DimmableSubtype
	{
		get;
		set;
	}

	public virtual void On()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Off()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Switch()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ONTime(object time)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Percentage(object %)
	{
		throw new System.NotImplementedException();
	}

	public virtual void RefreshState()
	{
		throw new System.NotImplementedException();
	}

}

