//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface HomeDeviceAbstract 
{
	object ID { get;set; }

	object Name { get;set; }

	Position Position { get;set; }

	TypeConnector TypeConnector { get;set; }

	Action Action { get;set; }

	TypeConnector1 TypeConnector1 { get;set; }

	Connector Connector { get;set; }

	void RefreshState();

}

