//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Node
{
	public virtual object Address
	{
		get;
		set;
	}

	public virtual object Name
	{
		get;
		set;
	}

	public virtual object ID
	{
		get;
		set;
	}

	public virtual Security Security
	{
		get;
		set;
	}

	public virtual Position Position
	{
		get;
		set;
	}

	public virtual TypeBase TypeBase
	{
		get;
		set;
	}

	public virtual TypeShield TypeShield
	{
		get;
		set;
	}

	public virtual TypeBase TypeBase1
	{
		get;
		set;
	}

	public virtual TypeShield TypeShield1
	{
		get;
		set;
	}

	public virtual Connector Connector
	{
		get;
		set;
	}

}

