//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Position
{
	public virtual object floor
	{
		get;
		set;
	}

	public virtual object X
	{
		get;
		set;
	}

	public virtual object Y
	{
		get;
		set;
	}

	public virtual object Movil
	{
		get;
		set;
	}

	public virtual object ID
	{
		get;
		set;
	}

	public virtual void CalculatePosition()
	{
		throw new System.NotImplementedException();
	}

	public Position(object floor, object x, object y, object movil)
	{
	}

}

