//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace HomeModel
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Zone
	{
		public virtual object Name
		{
			get;
			set;
		}

		public virtual object Height
		{
			get;
			set;
		}

		public virtual object Width
		{
			get;
			set;
		}

		public virtual object Map
		{
			get;
			set;
		}

	}
}

