//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Package2
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Theme
	{
		public virtual object Name
		{
			get;
			set;
		}

		public virtual object List<Delegates>
		{
			get;
			set;
		}

	}
}

