//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Package2
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Scheduler
	{
		public virtual TimeAction TimeAction
		{
			get;
			set;
		}

		public virtual void GetTimeActions(object HomeDevice)
		{
			throw new System.NotImplementedException();
		}

	}
}

