//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Conexion.Products
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Shield
	{
		public virtual object Dictionary<name, List<PinPort>>
		{
			get;
			set;
		}

	}
}

